service: doggo-service

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    endpointFile: localstack_endpoints.json
    lambda:
      mountCode: true
      autostart: true
provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 256
functions:
  api:
    handler: wsgi_handler.handler
    environment:
      DATABASE_URL:
    events:
      - http:
          method: post
          path: /events
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-localstack
